[package]
name = "wsclient"
version = "0.1.0"
authors = ["Michał Pokrywka <michal.pokrywka@twoupdigital.com>"]
edition = "2018"

[dependencies]
docopt = "1"
websocket = "0.22"
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
